:Author: anilgvnc
:Email: {guvencgrup2@gmail.com}
:Date: 15/11/2023
:Revision: version#
:License: Public Domain

= Project: {Arduino-Projects}

Microprocessors and Microcontrollers (COME 327) examples.

== Step 1: Installation

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Arduino-projects                => Arduino sketch folder
  ├── sketch_w1_delay.ino        => Week 1 examples
  ├── sketch_w2_button.ino       => Week 2 examples
  ├──                            => Week * examples
  └──                            => Week * examples
....

=== License
This project is released under a {} License.

=== Contributing
To contribute to this project please contact anilgvnc https://id.arduino.cc/anilgvnc

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
